name: 1088 PR Basic Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v7

        - name: Setup Python (should fail)
          id: setup-python
          # uses: kmasuda050/setup-python@feature/python-version-required
          uses: actions/setup-python@v7
          # with:
          #   python-version: "3.12"
          env:
            PYTHON_VERSION_REQUIRED: true
          continue-on-error: true

