name: Reproduce setup-python - 1317 - Matrix Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  reproduce:
    runs-on: ${{ matrix.os }}
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-15-intel]
        # python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        python-version: ["3.9.12", "3.9.13", "3.10.4", "3.10.5", "3.10.6", "3.10.7", "3.10.8", "3.10.9", "3.10.10", "3.10.11", "3.11.0", "3.11.1", "3.11.2", "3.11.3", "3.11.4", "3.11.5", "3.11.6", "3.11.7", "3.11.8", "3.11.9", "3.12.0", "3.12.1", "3.12.2", "3.12.3", "3.12.4", "3.12.5", "3.12.6", "3.12.7", "3.12.8", "3.12.9", "3.12.10", "3.13.0", "3.13.1", "3.13.2", "3.13.3", "3.13.4", "3.13.5", "3.13.6", "3.13.7", "3.13.8", "3.13.9", "3.13.10", "3.13.11", "3.13.12", "3.14.0", "3.14.1", "3.14.2", "3.14.3"]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Installing Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        # uses: lmvysakh/setup-python@1317_fix
        with:
          python-version: "${{ matrix.python-version }}"
          pip-version: "26.1.2"