name: Reproduce setup-python - 1317

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  reproduce:
    runs-on: macos-latest
    name: "Checking error"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Installing Python 3.10
        uses: actions/setup-python@v6
        # uses: lmvysakh/setup-python@1317_fix_annotation
        with:
          python-version: "3.10"
          pip-version: "25.0.1"
      
          