name: Test Mac 15

on: 
  workflow_dispatch:
  push:
     branches: [ "main" ]
  # pull_request:
  #    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: lmvysakh/python-versions@check_12520
        with:
          python-version-file: '.python-version'
          check-latest: true
      - name: Verify Python version
        run: python --version