name: pip-testing

on:
  workflow_dispatch:
  push:
      branches: [ "main" ]

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python
      uses: priyagupta108/setup-python@pip-version-input
      with:
        python-version : '3.9'
        pip-version: '24'
        cache: 'poetry'
       
         
    - name: Check pip version
      run: pip --version
    - run: pip install poetry