name: pip-testing

on:
  workflow_dispatch:
  push:
      branches: [ "main" ]

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
        python-version: ['pypy3.8', 'pypy3.9', 'pypy3.10', 'pypy3.11']
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: lmvysakh/setup-python@test_pr_1129
      with:
        python-version: '${{ matrix.python-version }}'
        pip-version: '23'

    - name: Check pip version
      run: pip --version