name: pip-testing

on:
  workflow_dispatch:
  push:
      branches: [ "main" ]


jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: priyagupta108/setup-python@pip-version-input
      with:
        python-version: 'graalpy-24.0.2' 
        pip-version: '23'

    - name: Check pip version
      run: pip --version