name: Test pip cache
on:
  workflow_dispatch:
  push:
      branches: [ "main" ]
jobs:
  setup-python-with-pr:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [imagegenteam-win2022-16cores, imagegenteam-win2019-16cores, imagegenteam-ubuntu2204-16cores, imagegenteam-linux-arm64-8-cores, macos-latest, windows-latest, ubuntu-22.04, ubuntu-latest, macos-13 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: priyagupta108/setup-python@pip-version-input
        with:
          python-version: '3.13'
          cache: 'pip'
          pip-version: '25.0.1'
      - run: pip install -r requirements.txt
