name: pip version from pipfile

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pipfile-version-functionality:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:  [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-11-arm]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python from Pipfile
        uses: aradkdj/setup-python@feature/add-version-parsing-from-Pipfile
        with:
          python-version-file: Pipfile
          pip-version: 24.1z6
          cache: 'pip'

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt