name: pip version from pipfile

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pipfile-version-functionality:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python from Pipfile
        uses: aradkdj/setup-python@feature/add-version-parsing-from-Pipfile
        with:
          python-version-file: Pipfile
          pip-version: '24'
          cache: 'pip'
          cache-dependency-path: requirements.txt
       
          
      - name: Check pip version
        run: pip --version
