name: pip version from pipfile

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pipfile-version-functionality:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python from Pipfile
        uses: lmvysakh/setup-python@check_1067
        with:
          python-version-file: Pipfile
          pip-version: '24.2'
          cache: 'poetry'
       
         
      - name: Check pip version
        run: pip --version

      - name: Install poetry
        run: pip install poetry

      - name: Check poetry version
        run: poetry --version