name: pip version from pipfile

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pip-cache-error:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python from Pipfile
        uses: lmvysakh/setup-python@check_1067
        with:
          python-version-file: Pipfile

      - name: Display python version
        run: python --version
