name: pip version from pipfile

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pipfile-version-functionality:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-11-arm]
        pip-version: ['24.1', '25.0.1']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python from Pipfile
        uses: aradkdj/setup-python@feature/add-version-parsing-from-Pipfile
        with:
          python-version-file: Pipfile
          pip-version: ${{ matrix.pip-version }}
  

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt  