name: Pip version from pipfile

on:
  workflow_dispatch:
  push:

jobs:
  test-cache:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-11-arm]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python from pipfile
        uses: aradkdj/setup-python@feature/add-version-parsing-from-Pipfile
        with:
          python-version-file: Pipfile
          pip-version: 24.1
    

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt    

  test-v5:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-11-arm]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python from pipfile
        uses: aradkdj/setup-python@feature/add-version-parsing-from-Pipfile
        with:
           python-version-file: Pipfile
          

      - name: Verify pip version
        run: pip --version

      - run: pip install -r requirements.txt 