name: Test Setup Python Root Warning - 1217

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]


jobs:
  check-warning:
    runs-on: self-hosted # Modify this to match your runner label
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python version
        run: python --version

      - name: Install pip package (to trigger warning)
        run: |
          pip install --upgrade pip
        continue-on-error: true

      - name: Print pip location
        run: which pip

      - name: Print pip config (for debugging)
        run: pip config list