name: "Github-hosted - Directory Junction - Minimal"

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2025, windows-2022, windows-2025-vs2026,windows-11-arm]

    steps:

      - name: Create junction to bypass spaces in tool cache path
        shell: powershell
        run: |
          if (-not (Test-Path "C:\Hosted Tool Cache")) { New-Item -ItemType Directory -Path "C:\Hosted Tool Cache" }
          if (Test-Path "C:\ToolCache") { cmd /c rmdir C:\ToolCache }
          cmd /c mklink /J C:\ToolCache "C:\Hosted Tool Cache"
          "AGENT_TOOLSDIRECTORY=C:\ToolCache" | Out-File -FilePath $env:GITHUB_ENV -Append


      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          # cache: "pip"
          # cache-dependency-path: "requirements.txt"  


      - name: Verify
        shell: powershell
        run: |
          python --version
          python -m pip --version