name: check wget 2
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Architecture:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
            os: [self-hosted]
            
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # - name: Clear dotnet cache
      #   if: runner.os != 'Windows'
      #   run: rm -rf $HOME/.dotnet
      # - name: Clear dotnet cache (Windows)
      #   if: runner.os == 'Windows'
      #   run: Remove-Item -Recurse -Force $env:USERPROFILE\.dotnet
      #   shell: pwsh
      # - uses: actions/setup-dotnet@v5
      - uses: mahabaleshwars/setup-dotnet@feature/497-dotnet-version-latest-keyword
        with:
         dotnet-version: 'latest'
         dotnet-channel: sts
      - run: dotnet --info
