name: Setup Python Root Warning Test - 3
on:
  workflow_dispatch:
jobs:
  pip-root-warning:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Ensure pip is installed
        run: python3 -m ensurepip --upgrade
      - name: Confirm user before root step
        run: whoami
      - name: Run pip as root to reproduce warning
        run: |
          echo "Running pip as root user..."
          sudo bash -c '
            whoami
            python3 -m pip install requests
          '
