name: Setup Python Root Pip Test
on:
  workflow_dispatch:
jobs:
  setup-python-root:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run pip as root to reproduce warning
        run: |
          sudo bash -c '
            whoami
            python3 -m pip install requests
          '









